[build]
  command = "npm install --include=dev && npm run build"
  publish = "dist"
  base = "."

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_ENV = "production"
  VITE_SUPABASE_URL = "https://your-project-id.supabase.co"
  VITE_SUPABASE_ANON_KEY = "your-anon-key"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 